### PR TITLE
Promesa update and other mainly minor cosmetic improvements

### PR DESCRIPTION
**Pull request by niwinz**

### CODE REVIEW

**Comment by niwinz** [comment]
The advanced compilation fails but I don't understand why, is failing on `.send` method of `goog.net.XhrIo` :(

**Comment by niwinz** [comment]
I found the error, seems that XhrIo of testing does not comes with externs that makes fail on advanced compilation. But it is just testing issue.

**Comment by ghost** [comment]
Great, let me know when it's ready!

**Comment by niwinz** [comment]
Now it should be ready!

**Comment by niwinz** [comment]
@dialelo can you review it and release new version if everything is ok. It is a little bit blocking for the final postal release!

**Comment by ghost** [comment]
Thanks, just cut the 0.2.0 release.

**Pull request merged**
