### PR TITLE
add support for clj-http-lite client

### PR DESCRIPTION
**Pull request by k13gomez**
This PR adds support for `clj-http-lite` client, which is supported for GraalVM native compilation.

```
The author or authors of this code dedicate any and all copyright interest
in this code to the public domain. We make this dedication for the benefit of
the public at large and to the detriment of our heirs and successors. We
intend this dedication to be an overt act of relinquishment in perpetuity of
all present and future rights to this code under copyright law.
```

### CODE REVIEW

**Comment by k13gomez** [comment]
@niwinz can you take a look at this PR and let me know if you think it's suitable to include in the core `httpurr` library, as an alternative client implementation for the JVM (mainly to target GraalVM); otherwise I can create a separate library with the Client implementation.

**Comment by niwinz** [comment]
Thanks, i'll try to release a version soon with this client.

**Comment by k13gomez** [comment]
Thanks, can you release a SNAPSHOT version in the meantime?

**Comment by niwinz** [comment]
Done, `1.2.0-SNAPSHOT` uploaded.

**Pull request merged**
